/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import java.awt.geom.Point2D;

import javax.swing.*;

import gradle.controller.EnemyController;
import gradle.controller.Update;
import gradle.model.EnemyModel;
import gradle.model.EnemyType;
import gradle.model.EpsilonModel;
import gradle.view.GameFrame;
import gradle.view.GamePanel;
import java.awt.GraphicsEnvironment;
import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.TimeUnit;

public class App {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            GameFrame.getINSTANCE();
            GamePanel.getINSTANCE();
            GamePanel.getINSTANCE().repaint();

            // add items
            new EpsilonModel();
            EnemyModel.create(new Point2D.Double(450, 400), EnemyType.triangle);
            // new En emyModel(new Point2D.Double(450, 245), EnemyType.triangle);
            // new EnemyModel(new Point2D.Double(50, 360), EnemyType.square);
            // new EnemyModel(new Point2D.Double(450, 400), EnemyType.triangle);
            // new EnemyModel(new Point2D.Double(170, 50), EnemyType.square);
            Update update = new Update();
            new Timer().scheduleAtFixedRate(new TimerTask() {
                @Override
                public void run() {
                    // Print and reset counts
                    // System.out.println("UPS: " + update.upsCount + ", FPS: " + update.fpsCount);
                    update.upsCount = 0;
                    update.fpsCount = 0;
                }
            }, 1000, 1000);
        });
    }
}
