/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import java.awt.geom.Point2D;

import javax.swing.*;

import gradle.controller.Update;
import gradle.model.EnemyModel;
import gradle.model.EnemyType;
import gradle.model.EpsilonModel;
import gradle.view.GameFrame;
import gradle.view.GamePanel;

public class App {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            GameFrame.getINSTANCE();
            GamePanel.getINSTANCE();
            GamePanel.getINSTANCE().repaint();

            // add items
            new EpsilonModel();
            new EnemyModel(new Point2D.Double(200, 100) , EnemyType.square);
            new EnemyModel(new Point2D.Double(300, 100) , EnemyType.triangle);
            new Update();
        });
    }
}
