/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import javax.swing.*;

import gradle.controller.Update;
import gradle.model.EpsilonModel;
import gradle.view.GameFrame;
import gradle.view.GamePanel;

public class App {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            GameFrame.getINSTANCE();
            GamePanel.getINSTANCE();
            GamePanel.getINSTANCE().repaint();

            // add items
            new EpsilonModel();

            new Update();
        });
    }
}
